project:
  type: website
  output-dir: docs

website:
  title: "Paxton Schroeder"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: resume.qmd
        text: Resume

      - href: publications.qmd
        text: Publications

      - text: Projects
        href: projects.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    
editor: visual